---
version: "3.8"  # optional since v1.27.0
services:
  postgres:
    image: docker.io/postgis/postgis:14-3.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "15432:5432"
    volumes:
      - postgis-tw-rental:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
    restart: always
volumes:
  postgis-tw-rental:
